<?php

declare(strict_types=1);

/**
 * I semi dell'archivio pubblico: persone, eventi, nazioni.
 *
 * Li carica bin/importa-archivio.php. Ogni voce e' un istante e un luogo, con
 * la fonte e la classe Rodden dell'ora.
 *
 *   data, ora   com'erano scritte nella fonte, sull'orologio di allora
 *   orologio    quale orologio: LMT (tempo medio locale), RMT (tempo medio di
 *               Roma, in Italia dal 1866 al 1893), CET, EST...
 *   ut          lo stesso istante in Tempo Universale: e' questo che si
 *               calcola. L'importatore lo confronta col fuso del portale e
 *               segnala le differenze, che qui sono quasi sempre volute.
 *
 * Le date partono dal 1800 perche' da li' partono i file di effemeridi.
 *
 * @return list<array<string,mixed>>
 */

return [
    // --- Persone --------------------------------------------------
    [
        'nome'       => 'Albert Einstein',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1879-03-14',
        'ora'        => '11:30',
        'orologio'   => 'LMT',
        'ut'         => '1879-03-14 10:50',
        'luogo'      => 'Ulma, Germania',
        'lat'        => 48.3984,
        'lon'        => 9.9916,
        'fuso'       => 'Europe/Berlin',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Albert_Einstein',
        'nota'       => 'Fisico teorico, autore della relatività ristretta e generale. Premio Nobel per la fisica nel 1921.',
    ],
    [
        'nome'       => 'Marie Curie',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1867-11-07',
        'ora'        => '12:00',
        'orologio'   => 'LMT',
        'ut'         => '1867-11-07 10:36',
        'luogo'      => 'Varsavia, Polonia',
        'lat'        => 52.2298,
        'lon'        => 21.0118,
        'fuso'       => 'Europe/Warsaw',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Dariusz Proskurnicki). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Marie_Curie',
        'nota'       => 'Fisica e chimica polacca naturalizzata francese, pioniera dello studio della radioattività. Unica persona premiata con il Nobel in due discipline scientifiche diverse (fisica 1903, chimica 1911).',
    ],
    [
        'nome'       => 'Sigmund Freud',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1856-05-06',
        'ora'        => '18:30',
        'orologio'   => 'PMT',
        'ut'         => '1856-05-06 17:32',
        'luogo'      => 'Příbor (Freiberg in Mähren), Repubblica Ceca',
        'lat'        => 49.6409,
        'lon'        => 18.145,
        'fuso'       => 'Europe/Prague',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi col tempo medio di Praga (+0:57:44, in uso in Boemia e Moravia dal 1850); col tempo locale di Příbor si avrebbe 17:17; controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Sigmund_Freud',
        'nota'       => 'Neurologo austriaco, fondatore della psicoanalisi. Tra le sue opere principali L\'interpretazione dei sogni (1899).',
    ],
    [
        'nome'       => 'Enrico Fermi',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1901-09-29',
        'ora'        => '19:00',
        'orologio'   => 'CET',
        'ut'         => '1901-09-29 18:00',
        'luogo'      => 'Roma, Italia',
        'lat'        => 41.8919,
        'lon'        => 12.5113,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Michel Gauquelin). UT calcolato da noi dal fuso legale dell\'epoca (CET, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Enrico_Fermi',
        'nota'       => 'Fisico italiano, tra i padri della fisica nucleare; guidò la realizzazione del primo reattore nucleare nel 1942. Premio Nobel per la fisica nel 1938.',
    ],
    [
        'nome'       => 'Rita Levi-Montalcini',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1909-04-22',
        'ora'        => '23:00',
        'orologio'   => 'CET',
        'ut'         => '1909-04-22 22:00',
        'luogo'      => 'Torino, Italia',
        'lat'        => 45.0705,
        'lon'        => 7.6868,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Michel Gauquelin). UT calcolato da noi dal fuso legale dell\'epoca (CET, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Rita_Levi-Montalcini',
        'nota'       => 'Neurobiologa italiana, scopritrice del fattore di crescita nervoso (NGF). Premio Nobel per la medicina nel 1986 e senatrice a vita dal 2001.',
    ],
    [
        'nome'       => 'Guglielmo Marconi',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1874-04-25',
        'ora'        => '09:15',
        'orologio'   => 'RMT',
        'ut'         => '1874-04-25 08:25',
        'luogo'      => 'Bologna, Italia',
        'lat'        => 44.4938,
        'lon'        => 11.3387,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Sy Scholfield). UT calcolato da noi col tempo medio di Roma (RMT, +0:49:56, in vigore in Italia dal 1866 al 1893); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Guglielmo_Marconi',
        'nota'       => 'Inventore e imprenditore italiano, pioniere della telegrafia senza fili e della radio. Premio Nobel per la fisica nel 1909.',
    ],
    [
        'nome'       => 'Maria Montessori',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1870-08-31',
        'ora'        => '03:30',
        'orologio'   => 'RMT',
        'ut'         => '1870-08-31 02:40',
        'luogo'      => 'Chiaravalle, Italia',
        'lat'        => 43.6011,
        'lon'        => 13.3251,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Grazia Bordoni). UT calcolato da noi col tempo medio di Roma (RMT, +0:49:56, in vigore in Italia dal 1866 al 1893); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Maria_Montessori',
        'nota'       => 'Medico ed educatrice italiana, ideatrice del metodo pedagogico che porta il suo nome, diffuso in tutto il mondo.',
    ],
    [
        'nome'       => 'Nikola Tesla',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1856-07-10',
        'ora'        => '00:00',
        'orologio'   => 'LMT',
        'ut'         => '1856-07-09 22:59',
        'luogo'      => 'Smiljan, Croazia',
        'lat'        => 44.567,
        'lon'        => 15.317,
        'fuso'       => 'Europe/Zagreb',
        'rodden'     => 'B',
        'fonte'      => 'Astrotheme, Rodden B: biografia (raccolta di Lois Rodden). UT calcolato da noi dal tempo medio locale; nato a mezzanotte tra il 9 e il 10 luglio; controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Nikola_Tesla',
        'nota'       => 'Inventore e ingegnere elettrico di origine serba, naturalizzato statunitense. Contribuì in modo decisivo allo sviluppo dei sistemi a corrente alternata.',
    ],
    [
        'nome'       => 'Steve Jobs',
        'tipo'       => 'persona',
        'categoria'  => 'scienza',
        'data'       => '1955-02-24',
        'ora'        => '19:15',
        'orologio'   => 'PST',
        'ut'         => '1955-02-25 03:15',
        'luogo'      => 'San Francisco, Stati Uniti',
        'lat'        => 37.7749,
        'lon'        => -122.4194,
        'fuso'       => 'America/Los_Angeles',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi dal fuso legale dell\'epoca (PST, -8, senza ora legale); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Steve_Jobs',
        'nota'       => 'Imprenditore statunitense, cofondatore di Apple. Legato allo sviluppo del personal computer, dell\'iPod e dell\'iPhone.',
    ],
    [
        'nome'       => 'Pablo Picasso',
        'tipo'       => 'persona',
        'categoria'  => 'arte',
        'data'       => '1881-10-25',
        'ora'        => '23:15',
        'orologio'   => 'LMT',
        'ut'         => '1881-10-25 23:33',
        'luogo'      => 'Malaga, Spagna',
        'lat'        => 36.7202,
        'lon'        => -4.4203,
        'fuso'       => 'Europe/Madrid',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Filipe Ferreira). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Pablo_Picasso',
        'nota'       => 'Pittore e scultore spagnolo, tra i fondatori del cubismo. Tra le sue opere più note Les Demoiselles d\'Avignon e Guernica.',
    ],
    [
        'nome'       => 'Vincent van Gogh',
        'tipo'       => 'persona',
        'categoria'  => 'arte',
        'data'       => '1853-03-30',
        'ora'        => '11:00',
        'orologio'   => 'LMT',
        'ut'         => '1853-03-30 10:41',
        'luogo'      => 'Zundert, Paesi Bassi',
        'lat'        => 51.4717,
        'lon'        => 4.6556,
        'fuso'       => 'Europe/Amsterdam',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Michel Gauquelin). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Vincent_van_Gogh',
        'nota'       => 'Pittore olandese postimpressionista, autore di opere come I girasoli e Notte stellata. In vita ebbe scarso riconoscimento.',
    ],
    [
        'nome'       => 'Frida Kahlo',
        'tipo'       => 'persona',
        'categoria'  => 'arte',
        'data'       => '1907-07-06',
        'ora'        => '08:30',
        'orologio'   => 'LMT',
        'ut'         => '1907-07-06 15:07',
        'luogo'      => 'Coyoacán, Messico',
        'lat'        => 19.3467,
        'lon'        => -99.1617,
        'fuso'       => 'America/Mexico_City',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Frida_Kahlo',
        'nota'       => 'Pittrice messicana, nota per gli autoritratti e per un linguaggio figurativo legato alla cultura popolare del Messico.',
    ],
    [
        'nome'       => 'Luigi Pirandello',
        'tipo'       => 'persona',
        'categoria'  => 'letteratura',
        'data'       => '1867-06-28',
        'ora'        => '03:15',
        'orologio'   => 'RMT',
        'ut'         => '1867-06-28 02:25',
        'luogo'      => 'Agrigento, Italia',
        'lat'        => 37.3107,
        'lon'        => 13.5766,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Ed Steinbrecher). UT calcolato da noi col tempo medio di Roma (RMT, +0:49:56, in vigore in Italia dal 1866 al 1893); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Luigi_Pirandello',
        'nota'       => 'Drammaturgo e scrittore siciliano, autore di Il fu Mattia Pascal e Sei personaggi in cerca d\'autore. Premio Nobel per la letteratura nel 1934.',
    ],
    [
        'nome'       => 'Gabriele D\'Annunzio',
        'tipo'       => 'persona',
        'categoria'  => 'letteratura',
        'data'       => '1863-03-12',
        'ora'        => '08:00',
        'orologio'   => 'LMT',
        'ut'         => '1863-03-12 07:03',
        'luogo'      => 'Pescara, Italia',
        'lat'        => 42.4584,
        'lon'        => 14.2028,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Michel Gauquelin). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Gabriele_d\'Annunzio',
        'nota'       => 'Poeta, romanziere e drammaturgo abruzzese, figura centrale del decadentismo italiano. Nel 1919 guidò l\'impresa di Fiume.',
    ],
    [
        'nome'       => 'Grazia Deledda',
        'tipo'       => 'persona',
        'categoria'  => 'letteratura',
        'data'       => '1871-09-28',
        'ora'        => '02:00',
        'orologio'   => 'LMT',
        'ut'         => '1871-09-28 01:23',
        'luogo'      => 'Nuoro, Italia',
        'lat'        => 40.3199,
        'lon'        => 9.3257,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Grazia Bordoni). UT calcolato da noi dal tempo medio locale; la convenzione oraria sarda del 1871 è incerta (la carta di Astrotheme implica circa 01:24); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Grazia_Deledda',
        'nota'       => 'Scrittrice sarda, autrice di romanzi come Canne al vento. Prima e finora unica donna italiana Premio Nobel per la letteratura (1926).',
    ],
    [
        'nome'       => 'Ernest Hemingway',
        'tipo'       => 'persona',
        'categoria'  => 'letteratura',
        'data'       => '1899-07-21',
        'ora'        => '08:00',
        'orologio'   => 'CST',
        'ut'         => '1899-07-21 14:00',
        'luogo'      => 'Oak Park, Stati Uniti',
        'lat'        => 41.885,
        'lon'        => -87.7845,
        'fuso'       => 'America/Chicago',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Sy Scholfield). UT calcolato da noi dal fuso legale dell\'epoca (CST, -6); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Ernest_Hemingway',
        'nota'       => 'Scrittore e giornalista statunitense, autore di Addio alle armi e Il vecchio e il mare. Premio Nobel per la letteratura nel 1954.',
    ],
    [
        'nome'       => 'Umberto Eco',
        'tipo'       => 'persona',
        'categoria'  => 'letteratura',
        'data'       => '1932-01-05',
        'ora'        => '18:30',
        'orologio'   => 'CET',
        'ut'         => '1932-01-05 17:30',
        'luogo'      => 'Alessandria, Italia',
        'lat'        => 44.9092,
        'lon'        => 8.6101,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Grazia Bordoni). UT calcolato da noi dal fuso legale dell\'epoca (CET, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Umberto_Eco',
        'nota'       => 'Semiologo, filosofo e romanziere italiano, autore di Il nome della rosa (1980) e di numerosi saggi di semiotica.',
    ],
    [
        'nome'       => 'Giuseppe Verdi',
        'tipo'       => 'persona',
        'categoria'  => 'musica',
        'data'       => '1813-10-10',
        'ora'        => '20:00',
        'orologio'   => 'LMT',
        'ut'         => '1813-10-10 19:20',
        'luogo'      => 'Roncole Verdi (Busseto), Italia',
        'lat'        => 44.9524,
        'lon'        => 10.0732,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Sy Scholfield). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Giuseppe_Verdi',
        'nota'       => 'Compositore italiano, tra i massimi autori di melodramma dell\'Ottocento: Nabucco, Rigoletto, La traviata, Aida.',
    ],
    [
        'nome'       => 'Giacomo Puccini',
        'tipo'       => 'persona',
        'categoria'  => 'musica',
        'data'       => '1858-12-22',
        'ora'        => '02:00',
        'orologio'   => 'LMT',
        'ut'         => '1858-12-22 01:18',
        'luogo'      => 'Lucca, Italia',
        'lat'        => 43.8437,
        'lon'        => 10.5045,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Giacomo_Puccini',
        'nota'       => 'Compositore lucchese, autore di opere come La bohème, Tosca, Madama Butterfly e Turandot (incompiuta).',
    ],
    [
        'nome'       => 'Luciano Pavarotti',
        'tipo'       => 'persona',
        'categoria'  => 'musica',
        'data'       => '1935-10-12',
        'ora'        => '01:40',
        'orologio'   => 'CET',
        'ut'         => '1935-10-12 00:40',
        'luogo'      => 'Modena, Italia',
        'lat'        => 44.6478,
        'lon'        => 10.9254,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Grazia Bordoni). UT calcolato da noi dal fuso legale dell\'epoca (CET, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Luciano_Pavarotti',
        'nota'       => 'Tenore modenese tra i più celebri del Novecento, noto anche per aver avvicinato l\'opera al grande pubblico.',
    ],
    [
        'nome'       => 'Ennio Morricone',
        'tipo'       => 'persona',
        'categoria'  => 'musica',
        'data'       => '1928-11-10',
        'ora'        => '22:25',
        'orologio'   => 'CET',
        'ut'         => '1928-11-10 21:25',
        'luogo'      => 'Roma, Italia',
        'lat'        => 41.8919,
        'lon'        => 12.5113,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Grazia Bordoni). UT calcolato da noi dal fuso legale dell\'epoca (CET, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Ennio_Morricone',
        'nota'       => 'Compositore e direttore d\'orchestra romano, autore di centinaia di colonne sonore. Premio Oscar alla carriera (2007) e per The Hateful Eight (2016).',
    ],
    [
        'nome'       => 'Sophia Loren',
        'tipo'       => 'persona',
        'categoria'  => 'cinema',
        'data'       => '1934-09-20',
        'ora'        => '14:10',
        'orologio'   => 'CET',
        'ut'         => '1934-09-20 13:10',
        'luogo'      => 'Roma, Italia',
        'lat'        => 41.8919,
        'lon'        => 12.5113,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Grazia Bordoni). UT calcolato da noi dal fuso legale dell\'epoca (CET, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Sophia_Loren',
        'nota'       => 'Attrice italiana, prima interprete a vincere l\'Oscar come migliore attrice per un film non in lingua inglese (La ciociara, 1962).',
    ],
    [
        'nome'       => 'Pier Paolo Pasolini',
        'tipo'       => 'persona',
        'categoria'  => 'cinema',
        'data'       => '1922-03-05',
        'ora'        => '06:30',
        'orologio'   => 'CET',
        'ut'         => '1922-03-05 05:30',
        'luogo'      => 'Bologna, Italia',
        'lat'        => 44.4938,
        'lon'        => 11.3387,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Ed Steinbrecher). UT calcolato da noi dal fuso legale dell\'epoca (CET, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Pier_Paolo_Pasolini',
        'nota'       => 'Poeta, scrittore e regista bolognese, autore di Ragazzi di vita e di film come Accattone e Il Vangelo secondo Matteo. Morì assassinato a Ostia nel 1975.',
    ],
    [
        'nome'       => 'Marilyn Monroe',
        'tipo'       => 'persona',
        'categoria'  => 'cinema',
        'data'       => '1926-06-01',
        'ora'        => '09:30',
        'orologio'   => 'PST',
        'ut'         => '1926-06-01 17:30',
        'luogo'      => 'Los Angeles, Stati Uniti',
        'lat'        => 34.0522,
        'lon'        => -118.2437,
        'fuso'       => 'America/Los_Angeles',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Bob Garner). UT calcolato da noi dal fuso legale dell\'epoca (PST, -8, senza ora legale); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Marilyn_Monroe',
        'nota'       => 'Attrice e cantante statunitense (nata Norma Jeane Mortenson), tra le figure più note del cinema hollywoodiano degli anni Cinquanta.',
    ],
    [
        'nome'       => 'Friedrich Nietzsche',
        'tipo'       => 'persona',
        'categoria'  => 'filosofia',
        'data'       => '1844-10-15',
        'ora'        => '10:00',
        'orologio'   => 'LMT',
        'ut'         => '1844-10-15 09:12',
        'luogo'      => 'Röcken, Germania',
        'lat'        => 51.2408,
        'lon'        => 12.1154,
        'fuso'       => 'Europe/Berlin',
        'rodden'     => 'B',
        'fonte'      => 'Astrotheme, Rodden B: biografia (raccolta di Sy Scholfield). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Friedrich_Nietzsche',
        'nota'       => 'Filosofo e filologo tedesco, autore di Così parlò Zarathustra e Al di là del bene e del male.',
    ],
    [
        'nome'       => 'Jean-Paul Sartre',
        'tipo'       => 'persona',
        'categoria'  => 'filosofia',
        'data'       => '1905-06-21',
        'ora'        => '18:45',
        'orologio'   => 'PMT',
        'ut'         => '1905-06-21 18:36',
        'luogo'      => 'Parigi, Francia',
        'lat'        => 48.8534,
        'lon'        => 2.3488,
        'fuso'       => 'Europe/Paris',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Didier Geslain). UT calcolato da noi col tempo medio di Parigi (PMT, +0:09:21, ora legale francese fino al 1911); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Jean-Paul_Sartre',
        'nota'       => 'Filosofo e scrittore francese, principale esponente dell\'esistenzialismo. Rifiutò il Premio Nobel per la letteratura nel 1964.',
    ],
    [
        'nome'       => 'Giuseppe Garibaldi',
        'tipo'       => 'persona',
        'categoria'  => 'politica',
        'data'       => '1807-07-04',
        'ora'        => '06:00',
        'orologio'   => 'LMT',
        'ut'         => '1807-07-04 05:31',
        'luogo'      => 'Nizza, Francia',
        'lat'        => 43.7031,
        'lon'        => 7.2661,
        'fuso'       => 'Europe/Paris',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Arthur Blackwell). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Giuseppe_Garibaldi',
        'nota'       => 'Generale e patriota, figura di primo piano del Risorgimento; guidò la spedizione dei Mille (1860).',
    ],
    [
        'nome'       => 'Winston Churchill',
        'tipo'       => 'persona',
        'categoria'  => 'politica',
        'data'       => '1874-11-30',
        'ora'        => '01:30',
        'orologio'   => 'GMT',
        'ut'         => '1874-11-30 01:30',
        'luogo'      => 'Woodstock (Blenheim Palace), Regno Unito',
        'lat'        => 51.8485,
        'lon'        => -1.3513,
        'fuso'       => 'Europe/London',
        'rodden'     => 'A',
        'fonte'      => 'Astrotheme, Rodden A: memoria dell\'interessato o di familiari, o autobiografia (raccolta di Lois Rodden). UT calcolato da noi assumendo il GMT, in uso di fatto in Gran Bretagna dal 1847; controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Winston_Churchill',
        'nota'       => 'Statista britannico, primo ministro del Regno Unito durante la seconda guerra mondiale e di nuovo dal 1951 al 1955. Premio Nobel per la letteratura nel 1953.',
    ],
    [
        'nome'       => 'Elisabetta II',
        'tipo'       => 'persona',
        'categoria'  => 'politica',
        'data'       => '1926-04-21',
        'ora'        => '02:40',
        'orologio'   => 'BST',
        'ut'         => '1926-04-21 01:40',
        'luogo'      => 'Londra (Mayfair), Regno Unito',
        'lat'        => 51.5085,
        'lon'        => -0.1257,
        'fuso'       => 'Europe/London',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Didier Geslain). UT calcolato da noi dal fuso legale dell\'epoca (ora estiva britannica, in vigore dal 18/04/1926, +1); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Elizabeth_II',
        'nota'       => 'Regina del Regno Unito e degli altri reami del Commonwealth dal 1952 al 2022, il regno più lungo della storia britannica.',
    ],
    [
        'nome'       => 'John Fitzgerald Kennedy',
        'tipo'       => 'persona',
        'categoria'  => 'politica',
        'data'       => '1917-05-29',
        'ora'        => '15:00',
        'orologio'   => 'EST',
        'ut'         => '1917-05-29 20:00',
        'luogo'      => 'Brookline, Stati Uniti',
        'lat'        => 42.3318,
        'lon'        => -71.1212,
        'fuso'       => 'America/New_York',
        'rodden'     => 'A',
        'fonte'      => 'Astrotheme, Rodden A: memoria dell\'interessato o di familiari, o autobiografia (raccolta di Lois Rodden). UT calcolato da noi dal fuso legale dell\'epoca (EST, -5, senza ora legale); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/John_Fitzgerald_Kennedy',
        'nota'       => '35º presidente degli Stati Uniti dal 1961. Fu assassinato a Dallas il 22 novembre 1963.',
    ],
    [
        'nome'       => 'Martin Luther King',
        'tipo'       => 'persona',
        'categoria'  => 'politica',
        'data'       => '1929-01-15',
        'ora'        => '12:00',
        'orologio'   => 'CST',
        'ut'         => '1929-01-15 18:00',
        'luogo'      => 'Atlanta, Stati Uniti',
        'lat'        => 33.749,
        'lon'        => -84.388,
        'fuso'       => 'America/New_York',
        'rodden'     => 'A',
        'fonte'      => 'Astrotheme, Rodden A: memoria dell\'interessato o di familiari, o autobiografia (raccolta di Lois Rodden). UT calcolato da noi: nel 1929 Atlanta seguiva l\'ora del Centro (CST, -6); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Martin_Luther_King',
        'nota'       => 'Pastore battista statunitense e leader del movimento per i diritti civili. Premio Nobel per la pace nel 1964; fu assassinato nel 1968.',
    ],
    [
        'nome'       => 'Mahatma Gandhi',
        'tipo'       => 'persona',
        'categoria'  => 'politica',
        'data'       => '1869-10-02',
        'ora'        => '07:08',
        'orologio'   => 'LMT',
        'ut'         => '1869-10-02 02:30',
        'luogo'      => 'Porbandar, India',
        'lat'        => 21.6422,
        'lon'        => 69.6093,
        'fuso'       => 'Asia/Kolkata',
        'rodden'     => 'C',
        'fonte'      => 'Astrotheme, Rodden C: ora rettificata a partire da un orario approssimativo (raccolta di Isaac Starkman). UT calcolato da noi dal tempo medio locale (longitudine del luogo); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Mahatma_Gandhi',
        'nota'       => 'Avvocato e leader politico indiano, guida del movimento per l\'indipendenza dell\'India fondato sulla nonviolenza. Fu assassinato nel 1948.',
    ],
    [
        'nome'       => 'Amelia Earhart',
        'tipo'       => 'persona',
        'categoria'  => 'esplorazione',
        'data'       => '1897-07-24',
        'ora'        => '23:30',
        'orologio'   => 'CST',
        'ut'         => '1897-07-25 05:30',
        'luogo'      => 'Atchison, Stati Uniti',
        'lat'        => 39.563,
        'lon'        => -95.1216,
        'fuso'       => 'America/Chicago',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi dal fuso legale dell\'epoca (CST, -6); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Amelia_Earhart',
        'nota'       => 'Aviatrice statunitense, prima donna a sorvolare l\'Atlantico in solitaria (1932). Scomparve sul Pacifico nel 1937.',
    ],
    [
        'nome'       => 'Neil Armstrong',
        'tipo'       => 'persona',
        'categoria'  => 'esplorazione',
        'data'       => '1930-08-05',
        'ora'        => '00:31',
        'orologio'   => 'EST',
        'ut'         => '1930-08-05 05:31',
        'luogo'      => 'Wapakoneta, Stati Uniti',
        'lat'        => 40.5678,
        'lon'        => -84.1936,
        'fuso'       => 'America/New_York',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi dal fuso legale dell\'epoca (EST, -5, senza ora legale); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Neil_Armstrong',
        'nota'       => 'Astronauta statunitense, comandante della missione Apollo 11 e primo uomo a camminare sulla Luna (20 luglio 1969).',
    ],
    [
        'nome'       => 'Fausto Coppi',
        'tipo'       => 'persona',
        'categoria'  => 'sport',
        'data'       => '1919-09-15',
        'ora'        => '21:30',
        'orologio'   => 'CEST',
        'ut'         => '1919-09-15 19:30',
        'luogo'      => 'Castellania Coppi, Italia',
        'lat'        => 44.7985,
        'lon'        => 8.9304,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Didier Geslain). UT calcolato da noi dal fuso legale dell\'epoca (ora estiva italiana del 1919, +2); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Fausto_Coppi',
        'nota'       => 'Ciclista piemontese, vincitore di cinque Giri d\'Italia e due Tour de France, tra i più grandi della storia del ciclismo.',
    ],
    [
        'nome'       => 'Muhammad Ali',
        'tipo'       => 'persona',
        'categoria'  => 'sport',
        'data'       => '1942-01-17',
        'ora'        => '18:35',
        'orologio'   => 'CST',
        'ut'         => '1942-01-18 00:35',
        'luogo'      => 'Louisville, Stati Uniti',
        'lat'        => 38.2542,
        'lon'        => -85.7594,
        'fuso'       => 'America/Kentucky/Louisville',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Michel Gauquelin). UT calcolato da noi dal fuso legale dell\'epoca (CST, -6); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Muhammad_Ali',
        'nota'       => 'Pugile statunitense (nato Cassius Clay), tre volte campione del mondo dei pesi massimi e figura pubblica di grande rilievo.',
    ],
    [
        'nome'       => 'Giovanni XXIII (Angelo Giuseppe Roncalli)',
        'tipo'       => 'persona',
        'categoria'  => 'religione',
        'data'       => '1881-11-25',
        'ora'        => '10:15',
        'orologio'   => 'RMT',
        'ut'         => '1881-11-25 09:25',
        'luogo'      => 'Sotto il Monte Giovanni XXIII, Italia',
        'lat'        => 45.7057,
        'lon'        => 9.5035,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'Astrotheme, Rodden AA: atto o registro di nascita (raccolta di Lois Rodden). UT calcolato da noi col tempo medio di Roma (RMT, +0:49:56, in vigore in Italia dal 1866 al 1893); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Pope_John_XXIII',
        'nota'       => 'Papa dal 1958 al 1963, promotore del Concilio Vaticano II. Proclamato santo nel 2014.',
    ],
    [
        'nome'       => 'Giovanni Paolo II (Karol Wojtyła)',
        'tipo'       => 'persona',
        'categoria'  => 'religione',
        'data'       => '1920-05-18',
        'ora'        => '17:30',
        'orologio'   => 'EET',
        'ut'         => '1920-05-18 15:30',
        'luogo'      => 'Wadowice, Polonia',
        'lat'        => 49.8834,
        'lon'        => 19.4929,
        'fuso'       => 'Europe/Warsaw',
        'rodden'     => 'A',
        'fonte'      => 'Astrotheme, Rodden A: memoria dell\'interessato o di familiari, o autobiografia (raccolta di Grazia Bordoni). UT calcolato da noi con l\'EET (+2) del database dei fusi per la Polonia 1919-1922 (con CEST il risultato non cambia); controllato su Ascendente e Medio Cielo pubblicati da Astrotheme.',
        'url'        => 'https://www.astrotheme.com/astrology/Pope_John_Paul_II',
        'nota'       => 'Papa dal 1978 al 2005, primo pontefice polacco e primo non italiano dopo oltre quattro secoli. Proclamato santo nel 2014.',
    ],

    // --- Nazioni e istituzioni --------------------------------------------------
    [
        'nome'       => 'Proclamazione del Regno d\'Italia',
        'tipo'       => 'nazione',
        'categoria'  => 'fondazione',
        'data'       => '1861-03-17',
        'ora'        => '00:00',
        'orologio'   => 'LMT',
        'ut'         => '1861-03-16 23:29',
        'luogo'      => 'Torino, Italia',
        'lat'        => 45.0703,
        'lon'        => 7.6869,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'C',
        'fonte'      => 'Astrology Weekly (tema tradizionale, 0:00 Torino); UT calcolato dal tempo medio locale di Torino',
        'url'        => 'https://blog.astrologyweekly.com/countries/italy.php',
        'nota'       => 'Tema convenzionale per l\'inizio del giorno in cui fu promulgata la legge che conferiva a Vittorio Emanuele II il titolo di re d\'Italia; l\'ora della firma non è documentata. Esiste anche un tema alternativo per l\'apertura del primo Parlamento italiano (18 febbraio 1861).',
    ],
    [
        'nome'       => 'Nascita della Repubblica Italiana',
        'tipo'       => 'nazione',
        'categoria'  => 'fondazione',
        'data'       => '1946-06-10',
        'ora'        => '18:00',
        'orologio'   => 'CEST',
        'ut'         => '1946-06-10 16:00',
        'luogo'      => 'Roma (Montecitorio, Sala della Lupa), Italia',
        'lat'        => 41.901,
        'lon'        => 12.4787,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'B',
        'fonte'      => 'Wikipedia it, Nascita della Repubblica Italiana; tema usato anche da Astrology Weekly; UT calcolato (ora legale 1946)',
        'url'        => 'https://it.wikipedia.org/wiki/Nascita_della_Repubblica_Italiana',
        'nota'       => 'Segna la lettura dei risultati del referendum da parte della Corte di Cassazione, il tema più usato per la Repubblica; alternative sono il voto del 2 giugno e la proclamazione dei risultati definitivi del 18 giugno, sempre alle 18. In Italia vigeva l\'ora legale (UTC+2).',
    ],
    [
        'nome'       => 'Entrata in vigore della Costituzione italiana',
        'tipo'       => 'nazione',
        'categoria'  => 'costituzione',
        'data'       => '1948-01-01',
        'ora'        => '00:00',
        'orologio'   => 'CET',
        'ut'         => '1947-12-31 23:00',
        'luogo'      => 'Roma, Italia',
        'lat'        => 41.901,
        'lon'        => 12.4787,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'C',
        'fonte'      => 'Wikipedia it, Costituzione della Repubblica Italiana; UT calcolato',
        'url'        => 'https://it.wikipedia.org/wiki/Costituzione_della_Repubblica_Italiana',
        'nota'       => 'Mezzanotte convenzionale del giorno di entrata in vigore; la Costituzione fu approvata il 22 dicembre e promulgata il 27 dicembre 1947, senza un\'ora documentata per l\'entrata in vigore.',
    ],
    [
        'nome'       => 'Unione di Gran Bretagna e Irlanda (Regno Unito)',
        'tipo'       => 'nazione',
        'categoria'  => 'unione',
        'data'       => '1801-01-01',
        'ora'        => '00:00',
        'orologio'   => 'LMT',
        'ut'         => '1801-01-01 00:00',
        'luogo'      => 'Westminster, Londra, Regno Unito',
        'lat'        => 51.4995,
        'lon'        => -0.1248,
        'fuso'       => 'Europe/London',
        'rodden'     => 'C',
        'fonte'      => 'Campion, Book of World Horoscopes, 3a ed., pp. 343-344 (citato da Astrology, Eh?); UT calcolato (00:00:30)',
        'url'        => 'https://astrologyeh.ca/the-coronation-of-king-charles-iii/',
        'nota'       => 'Mezzanotte in cui entrò in vigore l\'Atto di Unione che creò il Regno Unito di Gran Bretagna e Irlanda: istante fissato per legge ma senza un evento cronometrato. È il tema del Regno Unito più usato in astrologia mondiale.',
    ],
    [
        'nome'       => 'Proclamazione dell\'Impero tedesco',
        'tipo'       => 'nazione',
        'categoria'  => 'fondazione',
        'data'       => '1871-01-18',
        'ora'        => '13:00',
        'orologio'   => 'LMT',
        'ut'         => '1871-01-18 12:51',
        'luogo'      => 'Versailles (Galleria degli Specchi), Francia',
        'lat'        => 48.8049,
        'lon'        => 2.1204,
        'fuso'       => 'Europe/Paris',
        'rodden'     => 'C',
        'fonte'      => 'Astrology Weekly (tema tradizionale); Preussen-Chronik rbb per la cerimonia a mezzogiorno; UT calcolato',
        'url'        => 'https://blog.astrologyweekly.com/countries/germany.php',
        'nota'       => 'Le cronache collocano la cerimonia nella Galleria degli Specchi intorno a mezzogiorno; le 13:00 sono l\'ora approssimativa della proclamazione usata dagli astrologi. Molti astrologi tedeschi preferiscono il tema della mezzanotte del 1° gennaio 1871 a Berlino.',
    ],
    [
        'nome'       => 'Riunificazione tedesca',
        'tipo'       => 'nazione',
        'categoria'  => 'unione',
        'data'       => '1990-10-03',
        'ora'        => '00:00',
        'orologio'   => 'CET',
        'ut'         => '1990-10-02 23:00',
        'luogo'      => 'Berlino (Reichstag), Germania',
        'lat'        => 52.5186,
        'lon'        => 13.3762,
        'fuso'       => 'Europe/Berlin',
        'rodden'     => 'A',
        'fonte'      => 'Wikipedia en, German reunification; Astrology Weekly; UT calcolato',
        'url'        => 'https://en.wikipedia.org/wiki/German_reunification',
        'nota'       => 'Mezzanotte in cui l\'adesione della RDT alla Repubblica Federale ebbe effetto giuridico, sottolineata dall\'alzabandiera a Berlino. L\'ora legale era finita il 30 settembre, quindi vigeva l\'ora solare (UTC+1).',
    ],
    [
        'nome'       => 'Quinta Repubblica francese',
        'tipo'       => 'nazione',
        'categoria'  => 'costituzione',
        'data'       => '1958-10-06',
        'ora'        => '18:30',
        'orologio'   => 'CET',
        'ut'         => '1958-10-06 17:30',
        'luogo'      => 'Parigi (Cancelleria, place Vendôme), Francia',
        'lat'        => 48.8675,
        'lon'        => 2.3294,
        'fuso'       => 'Europe/Paris',
        'rodden'     => 'C',
        'fonte'      => 'Campion, Book of World Horoscopes, p. 167 (citato da Astrology King); UT calcolato',
        'url'        => 'https://astrologyking.com/france-horoscope/',
        'nota'       => 'Ora approssimativa dell\'apposizione del sigillo dello Stato alla nuova Costituzione, secondo Campion. La Costituzione porta la data del 4 ottobre e fu pubblicata il 5; alcuni astrologi usano la mezzanotte del 5 ottobre.',
    ],
    [
        'nome'       => 'Firma dei Trattati di Roma (CEE ed Euratom)',
        'tipo'       => 'nazione',
        'categoria'  => 'unione',
        'data'       => '1957-03-25',
        'ora'        => '18:50',
        'orologio'   => 'CET',
        'ut'         => '1957-03-25 17:50',
        'luogo'      => 'Roma (Campidoglio, Sala degli Orazi e Curiazi), Italia',
        'lat'        => 41.8933,
        'lon'        => 12.4829,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'A',
        'fonte'      => 'Cronaca d\'epoca della Gazzetta del Mezzogiorno, ripubblicata online; UT calcolato',
        'url'        => 'https://www.lagazzettadelmezzogiorno.it/news/notizie-nascoste/59537/i-trattati-di-roma-quel-giorno-del-25-marzo-1957.html',
        'nota'       => 'La cronaca del 1957 colloca l\'inizio della cerimonia alle 18 e la conclusione delle firme alle 18:50; il tema segna la fine della firma. La CEE nacque giuridicamente il 1° gennaio 1958.',
    ],
    [
        'nome'       => 'Introduzione dell\'euro',
        'tipo'       => 'nazione',
        'categoria'  => 'moneta',
        'data'       => '1999-01-01',
        'ora'        => '00:00',
        'orologio'   => 'CET',
        'ut'         => '1998-12-31 23:00',
        'luogo'      => 'Francoforte sul Meno, Germania',
        'lat'        => 50.1109,
        'lon'        => 8.6821,
        'fuso'       => 'Europe/Berlin',
        'rodden'     => 'C',
        'fonte'      => 'Astrotheme (Introduction of the euro); UT calcolato',
        'url'        => 'https://www.astrotheme.com/astrology/Introduction_of_the_euro',
        'nota'       => 'Mezzanotte convenzionale in cui l\'euro divenne moneta scritturale degli Stati aderenti, collocata a Francoforte sede della BCE. Esistono temi alternativi per Bruxelles e per la fissazione dei tassi di conversione il 31 dicembre 1998.',
    ],
    [
        'nome'       => 'Indipendenza dell\'India',
        'tipo'       => 'nazione',
        'categoria'  => 'fondazione',
        'data'       => '1947-08-15',
        'ora'        => '00:00',
        'orologio'   => 'IST',
        'ut'         => '1947-08-14 18:30',
        'luogo'      => 'Nuova Delhi (Parliament House), India',
        'lat'        => 28.6172,
        'lon'        => 77.208,
        'fuso'       => 'Asia/Kolkata',
        'rodden'     => 'A',
        'fonte'      => 'Wikipedia en, Tryst with Destiny; Astrology Weekly; UT calcolato',
        'url'        => 'https://en.wikipedia.org/wiki/Tryst_with_Destiny',
        'nota'       => 'Mezzanotte tra il 14 e il 15 agosto, istante fissato dall\'Indian Independence Act e celebrato in diretta dall\'Assemblea Costituente con il discorso di Nehru. È il tema dell\'India più usato.',
    ],
    [
        'nome'       => 'Proclamazione dello Stato di Israele',
        'tipo'       => 'nazione',
        'categoria'  => 'fondazione',
        'data'       => '1948-05-14',
        'ora'        => '16:00',
        'orologio'   => 'EET (UTC+2)',
        'ut'         => '1948-05-14 14:00',
        'luogo'      => 'Tel Aviv (Museo di Tel Aviv, Rothschild Boulevard), Israele',
        'lat'        => 32.0631,
        'lon'        => 34.7703,
        'fuso'       => 'Asia/Jerusalem',
        'rodden'     => 'A',
        'fonte'      => 'Campion, Book of World Horoscopes, p. 168 (citato da Astrology King); UT calcolato',
        'url'        => 'https://astrologyking.com/israel-horoscope/',
        'nota'       => 'Segna l\'apertura della seduta in cui Ben Gurion lesse la dichiarazione d\'indipendenza, iniziata puntualmente alle 16; la lettura terminò verso le 16:24 e la seduta verso le 16:32, orari usati da temi alternativi.',
    ],

    // --- Eventi --------------------------------------------------
    [
        'nome'       => 'Annuncio radiofonico dell\'Armistizio di Cassibile',
        'tipo'       => 'evento',
        'categoria'  => 'guerra',
        'data'       => '1943-09-08',
        'ora'        => '19:42',
        'orologio'   => 'CEST',
        'ut'         => '1943-09-08 17:42',
        'luogo'      => 'Roma (studi EIAR di via Asiago), Italia',
        'lat'        => 41.9224,
        'lon'        => 12.4658,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'A',
        'fonte'      => 'Wikipedia it, Proclama Badoglio dell\'8 settembre 1943; UT calcolato (ora legale 1943)',
        'url'        => 'https://it.wikipedia.org/wiki/Proclama_Badoglio_dell%278_settembre_1943',
        'nota'       => 'Segna la lettura del proclama di Badoglio ai microfoni dell\'EIAR, non la firma segreta dell\'armistizio avvenuta il 3 settembre a Cassibile. Eisenhower aveva già dato la notizia da Radio Algeri alle 18:30 ora italiana.',
    ],
    [
        'nome'       => 'Rivoluzione d\'Ottobre: presa del Palazzo d\'Inverno',
        'tipo'       => 'evento',
        'categoria'  => 'rivoluzione',
        'data'       => '1917-11-08',
        'ora'        => '02:10',
        'orologio'   => 'LMT',
        'ut'         => '1917-11-08 00:08',
        'luogo'      => 'Pietrogrado (Palazzo d\'Inverno), Russia',
        'lat'        => 59.9404,
        'lon'        => 30.3139,
        'fuso'       => 'Europe/Moscow',
        'rodden'     => 'DD',
        'fonte'      => 'Wikipedia en, October Revolution; Astrology Weekly riporta 02:12 LMT; UT calcolato dal tempo medio locale',
        'url'        => 'https://en.wikipedia.org/wiki/October_Revolution',
        'nota'       => 'Segna la resa del governo provvisorio nel Palazzo d\'Inverno, nella notte tra il 25 e il 26 ottobre del calendario giuliano; il colpo dell\'Aurora e l\'ingresso nel palazzo risalgono alla sera del 7 novembre. Non è chiaro se l\'orario delle cronache includa l\'ora legale russa del 1917: in tal caso l\'UT sarebbe un\'ora prima.',
    ],
    [
        'nome'       => 'Lancio dello Sputnik 1',
        'tipo'       => 'evento',
        'categoria'  => 'scienza',
        'data'       => '1957-10-04',
        'ora'        => '22:28',
        'orologio'   => 'MSK',
        'ut'         => '1957-10-04 19:28',
        'luogo'      => 'Tyuratam/Bajkonur (Sito 1), Kazakistan',
        'lat'        => 45.9203,
        'lon'        => 63.3422,
        'fuso'       => 'Asia/Qyzylorda',
        'rodden'     => 'AA',
        'fonte'      => 'RussianSpaceWeb (A. Zak): 22:28:34 ora di Mosca; Wikipedia en: 19:28:34 UTC',
        'url'        => 'https://www.russianspaceweb.com/sputnik_mission.html',
        'nota'       => 'Istante del decollo del razzo R-7 con il primo satellite artificiale, alle 22:28:34 ora di Mosca; all\'orologio locale del cosmodromo era già il 5 ottobre.',
    ],
    [
        'nome'       => 'Allunaggio dell\'Apollo 11',
        'tipo'       => 'evento',
        'categoria'  => 'esplorazione',
        'data'       => '1969-07-20',
        'ora'        => '15:17',
        'orologio'   => 'CDT',
        'ut'         => '1969-07-20 20:17',
        'luogo'      => 'Houston (Centro di controllo della missione), Stati Uniti',
        'lat'        => 29.5597,
        'lon'        => -95.09,
        'fuso'       => 'America/Chicago',
        'rodden'     => 'AA',
        'fonte'      => 'NASA NSSDCA, Apollo 11 Lunar Landing Mission (20:17:40 UT)',
        'url'        => 'https://nssdc.gsfc.nasa.gov/planetary/lunar/apollo11info.html',
        'nota'       => 'Contatto del modulo lunare Eagle con il suolo alle 20:17:40 UT. La carta e\' eretta per Houston, dove la missione era seguita e da dove parti\' il «Houston, Tranquility Base here»: case e angoli calcolati sul suolo lunare non avrebbero senso, perche\' la Luna non ha il nostro orizzonte. Il primo passo di Armstrong avvenne circa sei ore e mezza dopo, il 21 luglio verso le 02:56 UT.',
    ],
    [
        'nome'       => 'Bomba atomica su Hiroshima',
        'tipo'       => 'evento',
        'categoria'  => 'guerra',
        'data'       => '1945-08-06',
        'ora'        => '08:15',
        'orologio'   => 'JST',
        'ut'         => '1945-08-05 23:15',
        'luogo'      => 'Hiroshima, Giappone',
        'lat'        => 34.3955,
        'lon'        => 132.4536,
        'fuso'       => 'Asia/Tokyo',
        'rodden'     => 'A',
        'fonte'      => 'Wikipedia en, Little Boy; UT calcolato',
        'url'        => 'https://en.wikipedia.org/wiki/Little_Boy',
        'nota'       => 'Sgancio della bomba alle 08:15 ora giapponese; l\'esplosione avvenne circa 44 secondi dopo, a circa 600 metri di quota sopra il centro della città.',
    ],
    [
        'nome'       => 'Caduta del Muro di Berlino',
        'tipo'       => 'evento',
        'categoria'  => 'politica',
        'data'       => '1989-11-09',
        'ora'        => '23:29',
        'orologio'   => 'CET',
        'ut'         => '1989-11-09 22:29',
        'luogo'      => 'Berlino (valico di Bornholmer Straße), Germania',
        'lat'        => 52.5549,
        'lon'        => 13.398,
        'fuso'       => 'Europe/Berlin',
        'rodden'     => 'B',
        'fonte'      => 'Wikipedia de, Grenzübergang Bornholmer Straße; UT calcolato',
        'url'        => 'https://de.wikipedia.org/wiki/Grenz%C3%BCbergang_Bornholmer_Stra%C3%9Fe',
        'nota'       => 'Segna l\'apertura completa del valico di Bornholmer Straße, il primo a cedere, decisa dal comandante Harald Jäger; la conferenza stampa di Schabowski si era chiusa verso le 19. Alcune fonti indicano 22:45 invece di 23:29-23:30.',
    ],
    [
        'nome'       => 'Incidente di Černobyl\'',
        'tipo'       => 'evento',
        'categoria'  => 'disastro',
        'data'       => '1986-04-26',
        'ora'        => '01:23',
        'orologio'   => 'MSD',
        'ut'         => '1986-04-25 21:23',
        'luogo'      => 'Centrale di Černobyl\' (reattore 4), Ucraina',
        'lat'        => 51.389,
        'lon'        => 30.099,
        'fuso'       => 'Europe/Kyiv',
        'rodden'     => 'AA',
        'fonte'      => 'Wikipedia en, Chernobyl disaster (01:23 MSD, UTC+4); UT calcolato',
        'url'        => 'https://en.wikipedia.org/wiki/Chernobyl_disaster',
        'nota'       => 'Esplosione del reattore 4 durante un test di sicurezza iniziato alle 01:23:04; l\'esplosione seguì di poche decine di secondi, sempre nel minuto 01:23 dell\'ora estiva di Mosca, allora in vigore anche in Ucraina.',
    ],
    [
        'nome'       => 'Collisione del Titanic con l\'iceberg',
        'tipo'       => 'evento',
        'categoria'  => 'disastro',
        'data'       => '1912-04-14',
        'ora'        => '23:40',
        'orologio'   => 'ora di bordo (ATS)',
        'ut'         => '1912-04-15 02:38',
        'luogo'      => 'Atlantico settentrionale (area del relitto del Titanic)',
        'lat'        => 41.7256,
        'lon'        => -49.9469,
        'fuso'       => 'Etc/GMT+3',
        'rodden'     => 'B',
        'fonte'      => 'Wikipedia en, Sinking of the Titanic (23:40 ora di bordo = 02:38 GMT)',
        'url'        => 'https://en.wikipedia.org/wiki/Sinking_of_the_Titanic',
        'nota'       => 'L\'orario è quello degli orologi di bordo, regolati sul mezzogiorno apparente della nave e circa 2 ore e 58 minuti indietro rispetto a Greenwich secondo le ricostruzioni. Le coordinate sono quelle del relitto, a poche miglia dal punto dell\'urto.',
    ],
    [
        'nome'       => 'Terremoto di Messina e Reggio Calabria',
        'tipo'       => 'evento',
        'categoria'  => 'disastro',
        'data'       => '1908-12-28',
        'ora'        => '05:20',
        'orologio'   => 'CET',
        'ut'         => '1908-12-28 04:20',
        'luogo'      => 'Stretto di Messina, Italia',
        'lat'        => 38.146,
        'lon'        => 15.687,
        'fuso'       => 'Europe/Rome',
        'rodden'     => 'AA',
        'fonte'      => 'INGV, archivio ASMI e catalogo CFTI: 04:20:27 GMT',
        'url'        => 'https://emidius.mi.ingv.it/ASMI/event/19081228_0420_000',
        'nota'       => 'Tempo origine strumentale della scossa principale (Mw 7,1) alle 04:20:27 GMT; epicentro in mare nello Stretto, con successivo maremoto.',
    ],
    [
        'nome'       => 'Attentati dell\'11 settembre: primo impatto',
        'tipo'       => 'evento',
        'categoria'  => 'guerra',
        'data'       => '2001-09-11',
        'ora'        => '08:46',
        'orologio'   => 'EDT',
        'ut'         => '2001-09-11 12:46',
        'luogo'      => 'New York (World Trade Center, Torre Nord), Stati Uniti',
        'lat'        => 40.7127,
        'lon'        => -74.0134,
        'fuso'       => 'America/New_York',
        'rodden'     => 'AA',
        'fonte'      => '9/11 Commission Report, cap. 1 (08:46:40); UT calcolato',
        'url'        => 'https://www.9-11commission.gov/report/911Report_Ch1.htm',
        'nota'       => 'Impatto del volo American Airlines 11 contro la Torre Nord alle 08:46:40 ora estiva della costa orientale, secondo la Commissione d\'inchiesta.',
    ],
    [
        'nome'       => 'Primo segnale radio transatlantico di Marconi',
        'tipo'       => 'evento',
        'categoria'  => 'scienza',
        'data'       => '1901-12-12',
        'ora'        => '12:30',
        'orologio'   => 'NST (tempo medio di St. John\'s)',
        'ut'         => '1901-12-12 16:00',
        'luogo'      => 'Signal Hill, St. John\'s, Terranova',
        'lat'        => 47.5696,
        'lon'        => -52.6818,
        'fuso'       => 'America/St_Johns',
        'rodden'     => 'B',
        'fonte'      => 'IEEE ETHW, Milestone Reception of Transatlantic Radio Signals 1901 (diario di Marconi); UT calcolato',
        'url'        => 'https://ethw.org/Milestones:Reception_of_Transatlantic_Radio_Signals,_1901',
        'nota'       => 'Prima delle tre ricezioni annotate da Marconi nel diario (12:30, 1:10 e 2:20), intese come ora locale di Terranova, coerente con la finestra di trasmissione di Poldhu dalle 15 alle 19 GMT. L\'unico testimone fu l\'assistente Kemp.',
    ],
];
